Main duplicate
Star-Academy/Summer1400-SE-Team17 pull request #1
Opened 2021-07-25 08:50 UTC by Siasor88

make the project clean

2021-07-25 12:58 UTC, Mir-Abedi approved these changes
nice cleaning! 😁

2021-07-25 12:58 UTC, Mir-Abedi commented on Phase01-Search/pom.xml
> +    <version>1.0-SNAPSHOT</version><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target>
i don't like this line

2021-07-25 15:02 UTC, Mir-Abedi commented
nice commit descriptions BTW! 😁

2021-07-27 13:28 UTC, mostmand requested changes

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/pom.xml
> +    <version>1.0-SNAPSHOT</version><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target>
Me too.
Can you speak Persian?😜

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Data.java
> +        positions = new ArrayList<>();
این خط لازم نیست چون جلوی خود تعریفش
initialize
شده

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Data.java
> +        positions = new ArrayList<>();
این خط لازم نیست چون جلوی خود تعریفش
initialize
شده

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Data.java
> +        URL url = getClass().getResource("EnglishData/" + indexDocument);
آدرس فولدر حاوی فایل‌ها به صورت
const
تعریف شود

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Data.java
> +        return new String(Files.readAllBytes(Paths.get(url.toURI())));
خیلی
inline
نوشته شده این خط یه کم متغیر تعریف کن

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Data.java
> +        return new String(Files.readAllBytes(Paths.get(url.toURI())));
در تبدیل آرایه‌ی بایت به استرینگ، از چه انکودینگی استفاده میشه؟ بهتره به طور
explicit
نوشته بشه مثلاً
UTF8

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/DatabaseReader.java
> +    @SneakyThrows
بهتره این
annotation
استفاده نشه و اکسپشن‌ها به درستی هندل یا
throw
شوند

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/DatabaseReader.java
> +    private static void addDocumentsToResult(ArrayList<Document> result, File[] filesList) throws IOException {
چرا این تابع خودش
result
رو نیو نمی‌کنه و در نهایت
return
کنه؟ بهتره این تابع به جای
void
بودن خروجی بده

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/DatabaseReader.java
> +            String content = new String(Files.readAllBytes(file.toPath()));
این خط و دو خط پایینش می‌تونن به عنوان تابع استخراج بشن مثلاً تابعی به اسم
createDocument

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/DatabaseReader.java
> +        URL url = DatabaseReader.class.getResource(directoryLocation);
این خط چی کار می‌کنه؟

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            FileReader reader = new FileReader("main/resources/data.json");
آدرس فایل به صورت
const
تعریف بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +        Gson gson = new Gson();
دمتون گرم ایندکس رو که ساختید تو فایل ذخیره کردید؟👌

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            FileWriter writer = new FileWriter("src/main/resources/data.json");
این چهار خط یه تابع بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +        } catch (FileNotFoundException e) {
کارهایی که جزء فلوی اصلی برنامه‌تون هستن بهتره با اکسپشن هندل نشن می‌تونید چک کنید اون فایل وجود داره یا نه به جای این که این اکسپشن رو کچ کنید

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            FileReader reader = new FileReader("main/resources/data.json");
خطوط مربوط به خواندن فایل جیسون که در
try
قرار دارند می‌تونن به عنوان تابع استخراج بشن

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            for (Data data : Parser.parseDocument(document)) {
فور داخل یه فور دیگه به عنوان تابع استخراج بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            if (word.charAt(0) == '+') {
فور و ایف‌های تودرتو کد رو ناخوانا می‌کنن تابع استخراج کنید

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            if (word.charAt(0) == '+') {
در سایر تابع‌هاتون هم این موضوع دیده میشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +        Gson gson = new Gson();
وظیفه‌ی خواندن از جیسون یا نوشتن در اون رو به یه کلاس دیگه بسپارید که این کلاس درگیر کار با فایل و سریالایز و دیسریالایز نباشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +            HashSet<Integer> documentsWithWord = new HashSet<>();
این خط و سه خط پایینش می‌تونه یه تابع بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +        for (int i = 0; i < words.length; ++i) {
به جای
for
از 
foreach
استفاده بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/InvertedIndex.java
> +                words[i] = words[i].charAt(0) + Parser.stemWord(words[i].substring(1));
به جای این که آرایه‌ی ورودی رو تغییر بدین یه آرایه‌ی جدید بسازید و عناصر جدید رو توی اون قرار بدید

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Main.java
> +            String command = scanner.nextLine().trim();
خواندن از کنسول و نوشتن در اون رو به یه کلاس دیگه بسپارید تا دغدغه‌ی رابط کاربری‌تون از دغدغه‌ی منطق برنامه جدا بشه

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Parser.java
> +        for (String sentence : sentences) {
این تابع خیلی طولانیه و فور و ایف‌های تودرتو ناخواناش کرده تابع استخراج کنید از توش

2021-07-27 13:28 UTC, mostmand commented on Phase01-Search/src/main/java/Parser.java
> +            if (tag.matches("[A-Z$]+") && !tag.equals("$")) {
این تابع هم خیلی
indentation
داره از استخراج تابع و 
guard clause
بهره ببرید
https://refactoring.guru/replace-nested-conditional-with-guard-clauses

2021-07-28 01:36 UTC, AlisaLC commented
** General Notes **:
```
classes could have been in a package
most of static classes can be converted to non-static ones
file addresses could have been defined as constants
```
**Main**:
```
methods could have been in a separate class
scanner gets extra inputs without action
run method could have been split into multiple methods
```
**InvertedIndex**:
```
getOrDefault(word, new ArrayList<>()) creates a new Arraylist either way for each iteration
most of the created JSON is filled with names instead of values, creating a custom JSON adapter can reduce the file size significantly
```
**Parser**:
```
some of the methods are a little long
lines 100 to 108 have bad variable names and can be replaced by:
data.computeIfAbsent(stemmedWord, Data::new).addPosition(indexOfWord);
```
The use of Apache OpenNLP and caching the indexes was good

2021-07-28 09:32 UTC, Siasor88 commented on Phase01-Search/src/main/java/DatabaseReader.java
> +        URL url = DatabaseReader.class.getResource(directoryLocation);
az file mikhone

2021-08-02 06:54 UTC, merged